from match_conditions.fuzzf import completely, partial_ratio, token_sort_ratio

match_conditions = {
    "hasAdvisor": token_sort_ratio,
    "hasBiaoSyong": token_sort_ratio,
    "hasBrother": token_sort_ratio,
    "hasBrotherInLaw": token_sort_ratio,
    "hasClassmate": token_sort_ratio,
    "hasColleague": token_sort_ratio,
    "hasCousin": token_sort_ratio,
    "hasDaughter": token_sort_ratio,
    "hasDescendants": token_sort_ratio,
    "hasFather": token_sort_ratio,
    "hasFatherInLaw": token_sort_ratio,
    "hasFirstDaughter": token_sort_ratio,
    "hasFirstSon": token_sort_ratio,
    "hasFriend": token_sort_ratio,
    "hasFriendship": token_sort_ratio,
    "hasGrandFather": token_sort_ratio,
    "hasGrandMother": token_sort_ratio,
    "hasGrandSon": token_sort_ratio,
    "hasGreatGrandSon": token_sort_ratio,
    "hasHired": token_sort_ratio,
    "hasHusband": token_sort_ratio,
    "hasIntroducer": token_sort_ratio,
    "hasKinship": token_sort_ratio,
    "hasKnown": token_sort_ratio,
    "hasMother": token_sort_ratio,
    "hasMotherGrandSon": token_sort_ratio,
    "hasNephew": token_sort_ratio,
    "hasOlderSister": token_sort_ratio,
    "hasParticipatePolitics": token_sort_ratio,
    "hasProceededWith": token_sort_ratio,
    "hasSon": token_sort_ratio,
    "hasSonInLaw": token_sort_ratio,
    "hasSpouse": token_sort_ratio,
    "hasStaffMemberWas": token_sort_ratio,
    "hasStudent": token_sort_ratio,
    "hasSubordinateWas": token_sort_ratio,
    "hasSupportedPolitics": token_sort_ratio,
    "hasTeacher": token_sort_ratio,
    "hasTeacherStudent": token_sort_ratio,
    "hasWife": token_sort_ratio,
    "hasWorkFor": token_sort_ratio,
    "hasYaji": token_sort_ratio,
    "hasYoungerBrother": token_sort_ratio,
    "hasYoungerSister": token_sort_ratio
}
